### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by yolikers** [esjdev/ci4-viacep#1]
Hi,
Please Add Perfect Money Payment Gateway in your Boostpanel repository.
I will be highly thankful to you

**Comment by esjdev** [comment]
> Hi, Please Add Perfect Money Payment Gateway in your Boostpanel repository. I will be highly thankful to you

https://github.com/esjdev/boostpanel/issues/13

**Comment by yolikers** [comment]
Bro i will pay for it for adding Perfect Money Gateway, mostly SMM services use Perfect money.
Please add it i will pay the reasonable charges you say. Your boostpanel is perfect just missim PM module.
Maybe you dont have to change your existing code just for adding new gateway
Thank you

**Comment by esjdev** [comment]
> Bro i will pay for it for adding Perfect Money Gateway, mostly SMM services use Perfect money. Please add it i will pay the reasonable charges you say. Your boostpanel is perfect just missim PM module. Maybe you dont have to change your existing code just for adding new gateway Thank you

I no longer provide support or do separate services for the boostpanel.
